CANONICAL_FORMS = {
    "no_relation": ["NR"],
    "org:founded_by": ["{obj}, founder of {subj} .",
                       "{obj}, who established {subj} .",
                       "{subj}, founded by {obj} .",
                       "{obj} was the founder of {subj} .",
                       "{subj} founder {obj} ."],
    "per:employee_of": ["{subj} is an employee of {obj} .",
                        "{subj} is the {predicate} of {obj} .",
                        "{obj}'s {predicate} {subj} .",
                        "{subj}, the {predicate} of {obj} .",
                        "{subj}, {obj}'s {predicate} .",
                        "{subj}, {predicate} of {obj} ."
                        "{obj} joined {subj} ."],
    "org:alternate_names": ["{subj} known as {obj} .",
                            "{subj}, formally known as {obj} .",
                            "{subj}, then called {obj} .",
                            "Called {subj} or {obj} ."],
    "per:cities_of_residence": ["{subj} lived in {obj} .",
                                "{subj} moved to {obj} .",
                                "{subj}'s home in {obj} .",
                                "{subj} grew up in {obj} .",
                                "{subj} who lived in {obj} ."],
    "per:children": ["{subj}'s child is {obj} .",
                     "{subj}'s {predicate} is {obj} ."],
    "per:title": ["{subj} is a {obj} ."],
    "per:siblings": ["{subj}'s sibling is {obj} .",
                     "{subj}'s {predicate}, {obj} .",
                     "{obj}, {subj}'s {predicate} ."],
    "per:religion": ["{subj}, a {obj} .",
                     "{subj} is {obj} person ."],
    "per:age": ["{subj} is {obj} years old .",
                "{subj} dies at age {obj} .",
                "{subj}, aged {obj} .",
                "{subj} reached the age of {obj} ."],
    "org:website": ["Find {subj} online in {obj} ."],
    "per:stateorprovinces_of_residence": ["{subj} lived in {obj} .",
                                          "{subj} moved to {obj} .",
                                          "{subj}'s home in {obj} .",
                                          "{subj} grew up in {obj} .",
                                          "{subj} who lived in {obj} ."],
    "org:member_of": ["{subj} is part of {obj} .",
                      "{subj} has join the {obj} .",
                      "{subj} is a member of {obj} .",
                      "{obj} is composed of {subj} ."],
    "org:top_members/employees": ["{obj} is the {predicate} of {subj} .",
                                  "{subj}'s {predicate} {obj} .",
                                  "{obj}, the {predicate} of {subj} .",
                                  "{obj}, {subj}'s {predicate} .",
                                  "{obj}, {predicate} of {subj} ."],
    "per:countries_of_residence": ["{subj} lived in {obj} .",
                                   "{subj} moved to {obj} .",
                                   "{subj}'s home in {obj} .",
                                   "{subj} grew up in {obj} .",
                                   "{subj} who lived in {obj} ."],
    "org:city_of_headquarters": ["{subj}, based in {obj} .",
                                 "{subj} is headquartered in {obj} .",
                                 "{subj}, an organization based in {obj} .",
                                 "{subj}, which is based in {obj} ."],
    "org:members": ["{obj} is part of {subj} .",
                    "{obj} has join the {subj} .",
                    "{obj} is a member of {subj} .",
                    "{subj} is composed of {obj} ."],
    "org:country_of_headquarters": ["{subj}, based in {obj} .",
                                    "{subj}, based in Dublin, {obj} .",
                                    "{subj} is headquartered in {obj} .",
                                    "{subj}, an organization based in {obj} .",
                                    "{subj}, which is based in {obj} ."],
    "per:spouse": ["{subj} is married to {obj} .",
                   "{subj} married {obj} .",
                   "{subj}'s {predicate} {obj} ."],
    "org:stateorprovince_of_headquarters": ["{subj}, based in {obj} .",
                                            "{subj} is based in {obj} .",
                                            "{subj} is headquartered in {obj} .",
                                            "{subj}, an organization based in {obj} .",
                                            "{subj}, which is based in {obj} ."],
    "org:number_of_employees/members": ["{subj} employes {obj} workers .",
                                        "{subj} is an organization with {obj} employees .",
                                        "{subj} has {obj} employees ."],
    "org:parents": ["{subj}, a unit of {obj} .",
                    "{subj} at {obj} .",
                    "{subj} is a division of {obj} .",
                    "{subj} is owned by {obj} ."],
    "org:subsidiaries": ["{obj}, a unit of {subj} .",
                         "{obj} at {subj} .",
                         "{obj} is a division of {subj} .",
                         "{obj} is owned by {subj} ."],
    "per:origin": ["{subj} is a {obj} native .",
                   "{obj} {subj} .",
                   "{subj} is a {obj} ."],
    "org:political/religious_affiliation": ["{obj} group {subj} ."],
    "per:other_family": ["{subj} and {obj} are family members .",
                         "{subj}'s {predicate} {obj} ."],
    "per:stateorprovince_of_birth": ["{subj} was born in {obj} .",
                                     "{subj} was born on January 1st in {obj} .",
                                     "{subj} was born in {obj} ."],
    "org:dissolved": ["{subj} was dissolved in {obj} .", 
                      "{subj} announced bankrupcy in {obj} ."],
    "per:date_of_death": ["{subj} died in {obj} .",
                          "{subj} died at his home in {obj} ."],
    "org:shareholders": ["{obj} acquired some of {subj} .",
                         "{obj} invested in {subj} .",
                         "{subj}'s shareholder {obj} ."],
    "per:alternate_names": ["{subj}, who was known as {obj} .",
                            "{subj}, whose real name is {obj} .",
                            "{subj}, then known as {obj} ."],
    "per:parents": ["{obj} is {subj}'s parent .",
                    "{subj}'s {predicate}, {obj} .",
                    "{obj}, {subj}'s {predicate} .",
                    "{obj}, {predicate} of {subj} ."],
    "per:schools_attended": ["{subj} graduated from {obj} .",
                             "{subj} received a degree from {obj} .",
                             "{subj} attended {obj} ."],
    "per:cause_of_death": ["{subj} died of {obj} .",
                           "{subj} died from {obj} ."],
    "per:city_of_death": ["{subj} died in {obj} .",
                          "{subj} died at his home in {obj} .",
                          "{subj} died at Sunday in {obj} ."],
    "per:stateorprovince_of_death": ["{subj} died in {obj} .",
                                     "{subj} died at his home in {obj} .",
                                     "{subj} died at Sunday in {obj} ."],
    "org:founded": ["{subj} was established in {obj} .",
                    "Founded {subj} in {obj} .",
                    "{subj}, established in {obj} .",
                    "The founder founded {subj} in {obj} ."],
    "per:country_of_birth": ["{subj} was born in {obj} .",
                             "{subj} was born on January 1st in {obj} .",
                             "{subj} was born in Berlin, {obj} ."],
    "per:date_of_birth": ["{subj} was born in {obj} .",
                          "{subj} was born on {obj} ."],
    "per:city_of_birth": ["{subj} was born in {obj} .",
                          "{subj} was born on January 1st in {obj} ."],
    "per:charges": ["{subj} was convicted of {obj} .",
                    "{subj} face {obj} among other charges ."],
    "per:country_of_death": ["{subj} died in {obj} .",
                             "{subj} died at his home in {obj} .",
                             "{subj} died at Sunday in {obj} ."]
}


PREDICATES = {"org:top_members/employees": {"chief operating officer": "chief operating officer",
                                            "executive director": "executive director", "director-general": "director-general",
                                            "director general": "director general", "chief executive": "chief executive",
                                            "vice president": "vice president", "vice chairman": "vice chairman", "executive": "executive",
                                            "president": "president", "spokesman": "spokesman", "chairman": "chairman", "director": "director",
                                            "general": "general", "manager": "manager", "editor": "editor", "fellow": "fellow", "chief": "chief",
                                            "owner": "owner", "owns": "owner", "own": "owner", "ceo": "ceo", "coo": "coo", "cto": "cto",
                                            "default": "head"},
 "per:children": {"son": "son", "daughter": "daughter",
                  "default": None},
 "per:siblings": {"brother": "brother", "sister": "sister",
                  "default": None},
 "per:spouse": {"wife": "wife", "husband": "husband",
                  "default": None},
 "per:parents": {"father": "father", "mother": "mother",
                  "default": None},
 "per:other_family": {"sister's husband": "sister's husband", "brother 's wife": "brother 's wife", "brother-in-law": "brother-in-law",
                      "sister-in-law": "sister-in-law", "grandchildren": "grandchildren", "stepdaughters": "stepdaughter",
                      "stepdaughter": "stepdaughter", "stepfathers": "stepfather", "stepmothers": "stepmother", "stepmother": "stepmother",
                      "stepfather": "stepfather", "grandchild": "grandchild", "daughters": "daughter", "daughter": "daughter",
                      "stepsons": "stepson", "children": "children", "engaged": "is engaged to", "husband": "husband", 
                      "stepson": "stepson", "cousin": "cousin", "fiance": "fiance", "nephew": "nephew", "child": "child",
                      "niece": "niece", "sons": "son", "wife": "wife", "son": "son",
                      "default": None},
}

PREDICATES["per:employee_of"] = PREDICATES["org:top_members/employees"]
PREDICATES["per:employee_of"]['default'] = None